sudo: false

language: node_js

node_js:
  - '10'
  - '12'

branches:
  only:
    - master
    - travis-ci

before_install:
  - npm install -g npm
  - npm install --no-package-lock --no-save
  - npm install -g istanbul coveralls uglify-js
